apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels: 
    app: webapp-2 #(To map it with the service)
    release: "1"
spec:
  containers:
  - name: webapp-2
    image: richardchesterwood/k8s-fleetman-queue:release1